OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: OrgUser
    Domain: orguser.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgViewer
    Domain: orgviewer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgAdmin
    Domain: orgadmin.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
