

services:
#  postgres:
#    image: postgres:15
#    container_name: ehrbase
#    restart: always
#    environment:
#      POSTGRES_DB: ehrbase
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#  spring-backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    restart: always
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demographic
#      SPRING_DATASOURCE_USERNAME: ehr_user
#      SPRING_DATASOURCE_PASSWORD: ehr_pass
#    ports:
#      - "8888:8888"

  ca.org1.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
    ports:
      - "7051:7051"
    volumes:
      - ./fabric/peer0:/var/hyperledger/production
    depends_on:
      - ca.org1.example.com

  orderer.example.com:
    image: hyperledger/fabric-orderer:2.5
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
    ports:
      - "7050:7050"
    volumes:
      - ./fabric/orderer:/var/hyperledger/production

#volumes:
#  pgdata:
